repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: master
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint.git
    rev: master
    hooks:
      - id: ansible-lint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks.git
    rev: master
    hooks:
      - id: markdownlint
