---
# icon tasks file for usb_hid_descriptor_tool
- name: Create a temporary directory for an icon
  tempfile:
    state: directory
  register: usb_hid_descriptor_tool_icon_tmp_directory
  notify: Remove temporary USB HID Descriptor Tool icon directory

- name: Install icoutils to extract an icon
  package:
    name: icoutils
  notify: Remove icoutils

- name: Extract an icon
  # Always extract the icon and find out if it needs to be updated later
  command: wrestool -o "{{ tmp_icon_file_full }}" -x --name='DT' --type=group_icon "{{ tmp_executable_full }}"  # noqa 301
